name: vault-warden

director_uuid: 93c01d2d-a2a5-49d8-8d02-389fd223a9cf

instance_groups:
- name: vault
  instances: 1
  azs: [z1]
  networks:
  - name: default
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  jobs:
  - name: vault
    release: vault
    properties:
      vault:
        backend:
          use_file: true


stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3147

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000


releases:
- name: vault
  version: latest