---
meta:
  name: blacksmith
  url: https://ci.vsphere.starkandwayne.com/
  target: sw
  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))
  github:
    owner: cloudfoundry-community
    repo:  blacksmith-boshrelease
    private_key:  (( vault "secret/pipelines/blacksmith-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/blacksmith-boshrelease/github:token" ))
  bosh-lite:
    target: https://10.58.111.49:25555
    deployment: blacksmith-warden
  slack:
    webhook: (( vault "secret/pipelines/blacksmith-boshrelease/slack:webhook" ))
    channel: "#cf-community-pipeline"
    blob_success:  '(( concat "$BUILD_PIPELINE_NAME: New version of $BUILD_JOB_NAME was detected, and updated in master. <" meta.url "/pipelines/$BUILD_PIPELINE_NAME| Cut a new release?>" ))'
    blob_failure:  '(( concat "$BUILD_PIPELINE_NAME: :airplane_arriving: <" meta.url "/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| Failed to update the blob for $BUILD_JOB_NAME>" ))'

groups:
  - name: blobs
    jobs:
      - safe

resources:
  - name: safe
    type: github-release
    source:
      user: jhunt
      repository: safe
      access_token: (( grab meta.github.access_token ))

jobs:
  - name: safe
    public: true
    plan:
    - aggregate:
      - { get: git }
      - { get: safe, trigger: true }
    - task: update-safe
      config:
        image: docker:///starkandwayne/concourse
        platform: linux
        inputs:
        - name: git
        - name: safe
        outputs:
        - name: pushme
        run:
          path: ./git/ci/scripts/update-blob
        params:
          REPO_ROOT:        git
          REPO_OUT:         pushme
          RELEASE_DIR:      safe
          BLOB:             safe
          BLOB_BINARY:      safe-linux-amd64
          BLOB_DESTINATION: safe/safe
          AWS_ACCESS_KEY:   (( grab meta.aws.access_key ))
          AWS_SECRET_KEY:   (( grab meta.aws.secret_key ))
          BRANCH:       (( grab meta.github.branch ))
      on_failure:
        put: notify
        params:
          channel:  (( grab meta.slack.channel ))
          username: (( grab meta.slack.username ))
          icon_url: (( grab meta.slack.icon ))
          text:     (( grab meta.slack.blob_failure ))
    - put: git
      params:
        rebase: true
        repository: pushme/git
      on_success:
        put: notify
        params:
          channel:  (( grab meta.slack.channel ))
          username: (( grab meta.slack.username ))
          icon_url: (( grab meta.slack.icon ))
          text:     (( grab meta.slack.blob_success ))
      on_failure:
        put: notify
        params:
          channel:  (( grab meta.slack.channel ))
          username: (( grab meta.slack.username ))
          icon_url: (( grab meta.slack.icon ))
          text:     (( grab meta.slack.blob_failure ))
