---
meta:
  name:    blacksmith
  release: Blacksmith
  target:  blacksmith@pipes
  url:     https://pipes.starkandwayne.com

  manifest:
    path: ci/manifest.yml

  bosh-lite:
    target:   https://10.128.4.73:25555
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))
    cacert:   ((thunder-dome.ca-certificate))

  aws:
    access_key: ((cfcommunity.access))
    secret_key: ((cfcommunity.secret))

  git:
    name:  Stark & Wayne CI Bot
    email: ci@starkandwayne.com

  github:
    owner:  blacksmith-community
    repo:   blacksmith-boshrelease
    branch: master
    private_key:  ((starkandwayne-bot-github.private-key))
    access_token: ((starkandwayne-bot-github.access-token))

  shout:
    url:      http://10.128.4.65:7109
    username: ((shout.username))
    password: ((shout.password))


jobs:
- name: blacksmith
  public: true
  plan:
  - in_parallel:
    - get: git
    - get: blacksmith
      trigger: true
      params:
        globs: [blacksmith-*.tar.bz2]
  - task: update-blacksmith
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: (( grab meta.image.name ))
          tag:        (( grab meta.image.tag ))
      inputs:
      - name: git
      - name: blacksmith
      outputs:
      - name: pushme
      run:
        path: ./git/ci/scripts/update-blob
      params:
        REPO_ROOT:   git
        REPO_OUT:    pushme
        BLOB_DIR:    blacksmith
        BLOB_NAME:   Blacksmith
        BLOB_BINARY: blacksmith-*.tar.bz2
        BLOB_URL:    https://github.com/cloudfoundry-community/blacksmith
        BLOB_DESTINATION: blacksmith/blacksmith-${VERSION}.tar.bz2
        BLOB_CLEANUP:     blacksmith/blacksmith.*
        AWS_ACCESS_KEY: (( grab meta.aws.access_key ))
        AWS_SECRET_KEY: (( grab meta.aws.secret_key ))
        BRANCH:         (( grab meta.github.branch ))
    on_success:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: update-blob job '$BUILD_JOB_NAME' succeeded.
        ok:      yes
        link:    (( grab meta.shout.links.build ))
    on_failure:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: update-blob job '$BUILD_JOB_NAME' failed.
        ok:      no
        link:    (( grab meta.shout.links.build ))

  - put: git
    params:
      rebase: true
      repository: pushme/git
    on_success:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: A new version of '$BUILD_JOB_NAME' has been added to the BOSH release.
        ok:      yes
        link:    (( grab meta.shout.links.pipeline ))
    on_failure:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: Failed to push blob changes to git (for '$BUILD_JOB_NAME').
        ok:      no
        link:    (( grab meta.shout.links.build ))

- name: safe
  public: true
  plan:
  - in_parallel:
    - get: git
    - get: safe
      trigger: true
      params:
        globs: [safe-linux-amd64]
  - task: update-safe
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: (( grab meta.image.name ))
          tag:        (( grab meta.image.tag ))
      inputs:
      - name: git
      - name: safe
      outputs:
      - name: pushme
      run:
        path: ./git/ci/scripts/update-blob
      params:
        REPO_ROOT:   git
        REPO_OUT:    pushme
        BLOB_DIR:    safe
        BLOB_NAME:   Safe
        BLOB_BINARY: safe-linux-amd64
        BLOB_URL:    https://github.com/starkandwayne/safe
        BLOB_DESTINATION: safe/safe
        BLOB_CLEANUP:     safe/safe.*
        AWS_ACCESS_KEY: (( grab meta.aws.access_key ))
        AWS_SECRET_KEY: (( grab meta.aws.secret_key ))
        BRANCH:         (( grab meta.github.branch ))
    on_success:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: update-blob job '$BUILD_JOB_NAME' succeeded.
        ok:      yes
        link:    (( grab meta.shout.links.build ))
    on_failure:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: update-blob job '$BUILD_JOB_NAME' failed.
        ok:      no
        link:    (( grab meta.shout.links.build ))

  - put: git
    params:
      rebase: true
      repository: pushme/git
    on_success:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: A new version of '$BUILD_JOB_NAME' has been added to the BOSH release.
        ok:      yes
        link:    (( grab meta.shout.links.pipeline ))
    on_failure:
      put: notify
      params:
        topic:   (( concat meta.shout.topic "-$BUILD_JOB_NAME" ))
        message: Failed to push blob changes to git (for '$BUILD_JOB_NAME').
        ok:      no
        link:    (( grab meta.shout.links.build ))

groups:
- name: blobs
  jobs:
    - blacksmith
    - safe

resources:
- name: blacksmith
  type: github-release
  source:
    user:         blacksmith-community
    repository:   blacksmith
    access_token: (( grab meta.github.access_token ))

- name: safe
  type: github-release
  source:
    user:         starkandwayne
    repository:   safe
    access_token: (( grab meta.github.access_token ))
